# Generated by Django 3.1.2 on 2020-10-22 03:38

from django.db import migrations, models
import imageprocessing.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imageuploadmodel',
            name='image',
            field=models.ImageField(upload_to=imageprocessing.models.image_directory),
        ),
    ]
