# Generated by Django 3.1.2 on 2020-10-23 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessing', '0002_auto_20201022_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageuploadmodel',
            options={'verbose_name': '이미지 처리', 'verbose_name_plural': '이미지 처리'},
        ),
        migrations.AlterModelTable(
            name='imageuploadmodel',
            table='image_table',
        ),
    ]
